spring.application.name=taskmanager
spring.h2.console.enabled=true

spring.datasource.url=jdbc:postgresql://localhost:5433/taskmanager
spring.datasource.username=heena
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
